### ISSUE TITLE
Gopher page for spacecookie

### ISSUE THREAD

**Issue by sternenseemann** [sternenseemann/spacecookie#21]
Really a shame that there is no self hosted page for spacecookie yet. Shouldn't be too hard to set up with existing NixOS infrastructure and my [tries towards generating project pages](https://code.sterni.lv/sm/tree/web/software/default.nix).

**Comment by hyperrealgopher** [comment]
I'm almost finished with [Burrow: Static Gopherhole Generator](https://github.com/hyperrealgopher/burrow).

**Comment by sternenseemann** [comment]
Opted to go with [this monstrosity](https://code.sterni.lv/sm/tree/inet/gopher/default.nix) in the end. Now live at <gopher://sterni.lv/1/spacecookie>.

**Comment by hyperrealgopher** [comment]
Looks great in my Gopher client [waffle](https://github.com/hyperrealgopher/waffle)! Thanks for creating a gopher page for this!

![Screenshot from 2020-12-28 10-07-33](https://user-images.githubusercontent.com/61403741/103234468-98572480-48f4-11eb-9ccc-2de1c51598b9.png)
