### ISSUE TITLE
More thorough filetypeMap?

### ISSUE THREAD

**Issue by hyperrealgopher** [sternenseemann/spacecookie#49]
I was poking through your code and noticed the `filetypeMap`.

Would you like a more thorough utility for such? I have a half-baked, but functional utility [filesig](https://github.com/hyperrealgopher/filesig) which provides a mapping for a ton of files based off of file signatures (and I think even file extensions? although hit's been a while). I can update this library if you are interested in it.

**Comment by sternenseemann** [comment]
I think I wanted to do this via #36.

**Comment by hyperrealgopher** [comment]
Sounds good! Sounds like this can be closed.
